# Form implementation generated from reading ui file 'MTTable.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MTTable(object):
    def setupUi(self, MTTable):
        MTTable.setObjectName("MTTable")
        MTTable.resize(462, 320)
        self.gridLayout = QtWidgets.QGridLayout(MTTable)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=MTTable)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.retranslateUi(MTTable)
        QtCore.QMetaObject.connectSlotsByName(MTTable)

    def retranslateUi(self, MTTable):
        _translate = QtCore.QCoreApplication.translate
        MTTable.setWindowTitle(_translate("MTTable", "MTT результаты"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MTTable", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MTTable", "Дата"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MTTable", "Соединение"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MTTable", "Линия"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MTTable", "EC50"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MTTable", "SE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MTTable = QtWidgets.QWidget()
    ui = Ui_MTTable()
    ui.setupUi(MTTable)
    MTTable.show()
    sys.exit(app.exec())
